services:

  mongo-db:
    container_name: mongo-db
    build: ./mongodb_rs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: flipboard
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - 27017:27017
    volumes:
      - ../Backend/database/mongodb_files/:/data/db
    networks:
      - mynetwork

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - mongo-db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      # estas son para no tener que poner el auth cada vez
      # que se abra mongo-express
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: pass
      # se conecta por la red interna a mongo-db (mongo-db:27017)
      ME_CONFIG_MONGODB_URL: "mongodb://admin:root@mongo-db:27017/flipboard?authSource=admin&directConnection=true"
    ports:
      - 8081:8081
    networks:
      - mynetwork

  api:
    container_name: api
    build: ./../Backend
    depends_on:
      - mongo-db
    environment:
      # se conecta por la red interna a mongo-db (mongo-db:27017)
      DATABASE_URL: "mongodb://admin:root@mongo-db:27017/flipboard?authSource=admin&directConnection=true"
      JWT_SECRET_KEY: "3z4OtpfVIEWrSoDWn5PXZ+QOcjYSfLoNNLQcTNRKQw8="
    ports:
      - 3100:3100
    networks:
      - mynetwork
    volumes:
      # Montar el directorio Backend en el contenedor para asi poder modificar el codigo sin tener que reconstruir la imagen
      - ./../Backend:/app

  # nextjs:
  #   container_name: frontend
  #   build: ./../Frontend
  #   environment:
  #     BACKEND_URL: "http://api:3100"
  #   ports:
  #    - 3000:3000
  #   networks:
  #     - mynetwork
  #   volumes:
  #     - ./../Frontend:/app

networks:
  mynetwork:
    driver: bridge
    
