services:

  mongo-db:
    container_name: mongo-db
    build: ./mongodb_rs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: flipboard
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - 27017:27017
    networks:
      - mynetwork

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    links:
      - mongo-db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      # estas son para no tener que poner el auth cada vez
      # que se abra mongo-express
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_URL: "mongodb://admin:root@mongo-db:27017/flipboard?authSource=admin&directConnection=true"
    ports:
      - 8081:8081
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
    
