services:

  mongo-db:
    container_name: mongo-db
    build: ./mongodb_rs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: flipboard
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - 27017:27017
    volumes:
      - ../Backend/database/mongodb_files/:/data/db
    networks:
      - mynetwork

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - mongo-db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      # estas son para no tener que poner el auth cada vez
      # que se abra mongo-express
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: pass
      # se conecta por la red interna a mongo-db (mongo-db:27017)
      ME_CONFIG_MONGODB_URL: "mongodb://admin:root@mongo-db:27017/flipboard?authSource=admin&directConnection=true"
    ports:
      - 8081:8081
    networks:
      - mynetwork

  api:
    container_name: api
    build: 
      context: ./../Backend
      target: prod
    depends_on:
      - mongo-db
    # environment:
    ports:
      - 3100:3100
    networks:
      - mynetwork
    volumes:
      # Montar el directorio Backend en el contenedor para asi poder modificar el codigo sin tener que reconstruir la imagen
      - ./../Backend:/app

  nextjs:
    container_name: frontend
    build: 
      context: ./../Frontend
      target: prod
    # environment:
     # BACKEND_URL: "http://api:3100"
    ports:
     - 3000:3000
    networks:
      - mynetwork
    # volumes:
    #   - ./../Frontend:/app
    #   - /app/node_modules

  mural-room-web-socket:
    container_name: mural-room-web-socket
    build: 
      context: ./../Mural/RoomWebSocket
      target: prod
    ports:
      - 3002:3002
    networks:
      - mynetwork
    # volumes:
    #   - ./../Mural/RoomWebSocket:/app

  mural-excalidraw:
    container_name: mural-excalidraw
    build: 
      context: ./../Mural/Excalidraw
      # target: prod
    ports:
      - 4000:80
    networks:
      - mynetwork
    depends_on:
      - mural-room-web-socket
    # Enable this for live reload (tarda bastante en recargar, pero funciona)
    # environment:
    #   - VITE_DOCKER=true
    # volumes:
    #   - ./../Mural/Excalidraw:/app
    #   # exclude node modules
    #   - /app/node_modules

networks:
  mynetwork:
    driver: bridge
    
