services:

  mongo-db:
    container_name: mongo-db
    image: alnrodriguez/flipboard-mongo-db:${FLIPBOARD_VERSION}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: flipboard
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    # ports:
    #   - 27017:27017
    volumes:
      - ../Backend/database/mongodb_files/:/data/db
    networks:
      - mynetwork

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - mongo-db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      # estas son para no tener que poner el auth cada vez
      # que se abra mongo-express
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: pass
      # se conecta por la red interna a mongo-db (mongo-db:27017)
      ME_CONFIG_MONGODB_URL: "mongodb://admin:root@mongo-db:27017/flipboard?authSource=admin&directConnection=true"
    ports:
      - 8081:8081
    networks:
      - mynetwork

  api:
    container_name: api
    image: alnrodriguez/flipboard-backend:${FLIPBOARD_VERSION}
    depends_on:
      - mongo-db
    # ports:
    #   - 3100:3100
    volumes:
      - ../Backend/calificaciones:/app/calificaciones
    networks:
      - mynetwork

  nextjs:
    container_name: frontend
    image: alnrodriguez/flipboard-frontend:${FLIPBOARD_VERSION}
    # ports:
    #  - 3000:3000
    networks:
      - mynetwork

  mural-room-web-socket:
    container_name: mural-room-web-socket
    image: alnrodriguez/flipboard-mural-room-web-socket:${FLIPBOARD_VERSION}
    # ports:
    #   - 3002:3002
    networks:
      - mynetwork

  mural-excalidraw:
    container_name: mural-excalidraw
    image: alnrodriguez/flipboard-mural-excalidraw:${FLIPBOARD_VERSION}
    # ports:
    #   - 4000:80
    networks:
      - mynetwork
    depends_on:
      - mural-room-web-socket
  
  nginx:
    image: alnrodriguez/flipboard-nginx:${FLIPBOARD_VERSION}
    container_name: nginx
    ports:
      - 80:8000
      - 443:443
      # - 3000:3000
      # - 3002:3002
      # - 3100:3100
      # - 4000:4000
    volumes:
      - ../nginx/etc/ssl:/etc/nginx/ssl:ro
    restart: always
    depends_on:
      - api
      - nextjs
      - mural-room-web-socket
      - mural-excalidraw
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge